version: "3.6"
services:
  # DB
  db:
    build:
      context: ./db
    ports:
      - ${DB_PORT}:5432

  # WEB
  web:
    build:
      context: ./web
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    volumes: 
      - /home/alex/git/podpisaka/server/web/gallery:/usr/src/podpisaka/gallery
volumes:
  etw-data-volume:
